// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agynio/api/ziti_management/v1/ziti_management.proto

package ziti_managementv1

import (
	v1 "github.com/agynio/tracing/.gen/go/agynio/api/identity/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_TYPE_UNSPECIFIED  ServiceType = 0
	ServiceType_SERVICE_TYPE_GATEWAY      ServiceType = 1
	ServiceType_SERVICE_TYPE_ORCHESTRATOR ServiceType = 2
	ServiceType_SERVICE_TYPE_LLM_PROXY    ServiceType = 4
	ServiceType_SERVICE_TYPE_TRACING      ServiceType = 5
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE_TYPE_GATEWAY",
		2: "SERVICE_TYPE_ORCHESTRATOR",
		4: "SERVICE_TYPE_LLM_PROXY",
		5: "SERVICE_TYPE_TRACING",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED":  0,
		"SERVICE_TYPE_GATEWAY":      1,
		"SERVICE_TYPE_ORCHESTRATOR": 2,
		"SERVICE_TYPE_LLM_PROXY":    4,
		"SERVICE_TYPE_TRACING":      5,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

// The type of OpenZiti service policy.
type ServicePolicyType int32

const (
	ServicePolicyType_SERVICE_POLICY_TYPE_UNSPECIFIED ServicePolicyType = 0
	ServicePolicyType_SERVICE_POLICY_TYPE_BIND        ServicePolicyType = 1
	ServicePolicyType_SERVICE_POLICY_TYPE_DIAL        ServicePolicyType = 2
)

// Enum value maps for ServicePolicyType.
var (
	ServicePolicyType_name = map[int32]string{
		0: "SERVICE_POLICY_TYPE_UNSPECIFIED",
		1: "SERVICE_POLICY_TYPE_BIND",
		2: "SERVICE_POLICY_TYPE_DIAL",
	}
	ServicePolicyType_value = map[string]int32{
		"SERVICE_POLICY_TYPE_UNSPECIFIED": 0,
		"SERVICE_POLICY_TYPE_BIND":        1,
		"SERVICE_POLICY_TYPE_DIAL":        2,
	}
)

func (x ServicePolicyType) Enum() *ServicePolicyType {
	p := new(ServicePolicyType)
	*p = x
	return p
}

func (x ServicePolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServicePolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[1].Descriptor()
}

func (ServicePolicyType) Type() protoreflect.EnumType {
	return &file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes[1]
}

func (x ServicePolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServicePolicyType.Descriptor instead.
func (ServicePolicyType) EnumDescriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{1}
}

type ManagedIdentity struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityId     string                 `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType   v1.IdentityType        `protobuf:"varint,3,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	ZitiServiceId  string                 `protobuf:"bytes,4,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagedIdentity) Reset() {
	*x = ManagedIdentity{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedIdentity) ProtoMessage() {}

func (x *ManagedIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedIdentity.ProtoReflect.Descriptor instead.
func (*ManagedIdentity) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedIdentity) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ManagedIdentity) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

func (x *ManagedIdentity) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

func (x *ManagedIdentity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAgentIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	WorkloadId    string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentIdentityRequest) Reset() {
	*x = CreateAgentIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityRequest) ProtoMessage() {}

func (x *CreateAgentIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentIdentityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateAgentIdentityRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

type CreateAgentIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	EnrollmentJwt  string                 `protobuf:"bytes,2,opt,name=enrollment_jwt,json=enrollmentJwt,proto3" json:"enrollment_jwt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAgentIdentityResponse) Reset() {
	*x = CreateAgentIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentIdentityResponse) ProtoMessage() {}

func (x *CreateAgentIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAgentIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateAgentIdentityResponse) GetEnrollmentJwt() string {
	if x != nil {
		return x.EnrollmentJwt
	}
	return ""
}

// Request to create and enroll an OpenZiti identity for an app.
type CreateAppIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppIdentityRequest) Reset() {
	*x = CreateAppIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppIdentityRequest) ProtoMessage() {}

func (x *CreateAppIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateAppIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAppIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *CreateAppIdentityRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// Response with enrolled OpenZiti credentials for an app identity.
type CreateAppIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityJson   []byte                 `protobuf:"bytes,2,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAppIdentityResponse) Reset() {
	*x = CreateAppIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppIdentityResponse) ProtoMessage() {}

func (x *CreateAppIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateAppIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateAppIdentityResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

// OpenZiti host.v1 config — tells the hosting sidecar where to forward traffic.
type HostV1Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostV1Config) Reset() {
	*x = HostV1Config{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostV1Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostV1Config) ProtoMessage() {}

func (x *HostV1Config) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostV1Config.ProtoReflect.Descriptor instead.
func (*HostV1Config) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{5}
}

func (x *HostV1Config) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HostV1Config) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HostV1Config) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// OpenZiti intercept.v1 config — tells dialing tunnelers which address to intercept.
type InterceptV1Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocols     []string               `protobuf:"bytes,1,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PortRanges    []*PortRange           `protobuf:"bytes,3,rep,name=port_ranges,json=portRanges,proto3" json:"port_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterceptV1Config) Reset() {
	*x = InterceptV1Config{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterceptV1Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterceptV1Config) ProtoMessage() {}

func (x *InterceptV1Config) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterceptV1Config.ProtoReflect.Descriptor instead.
func (*InterceptV1Config) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{6}
}

func (x *InterceptV1Config) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *InterceptV1Config) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *InterceptV1Config) GetPortRanges() []*PortRange {
	if x != nil {
		return x.PortRanges
	}
	return nil
}

// A port range for intercept.v1 config.
type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int32                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{7}
}

func (x *PortRange) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PortRange) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

type CreateServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "runner-{runnerId}", "app-{slug}", or "exposed-{id}"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// e.g. ["runner-services"], ["app-services"], or ["exposed-services"]
	RoleAttributes []string `protobuf:"bytes,2,rep,name=role_attributes,json=roleAttributes,proto3" json:"role_attributes,omitempty"`
	// Optional host.v1 config to create and attach to the service.
	// Used by Expose Service for port exposure.
	HostV1Config *HostV1Config `protobuf:"bytes,3,opt,name=host_v1_config,json=hostV1Config,proto3,oneof" json:"host_v1_config,omitempty"`
	// Optional intercept.v1 config to create and attach to the service.
	// Used by Expose Service for port exposure.
	InterceptV1Config *InterceptV1Config `protobuf:"bytes,4,opt,name=intercept_v1_config,json=interceptV1Config,proto3,oneof" json:"intercept_v1_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{8}
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetRoleAttributes() []string {
	if x != nil {
		return x.RoleAttributes
	}
	return nil
}

func (x *CreateServiceRequest) GetHostV1Config() *HostV1Config {
	if x != nil {
		return x.HostV1Config
	}
	return nil
}

func (x *CreateServiceRequest) GetInterceptV1Config() *InterceptV1Config {
	if x != nil {
		return x.InterceptV1Config
	}
	return nil
}

type CreateServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti service ID
	ZitiServiceId string `protobuf:"bytes,1,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	// The service name (echoed back)
	ZitiServiceName string `protobuf:"bytes,2,opt,name=ziti_service_name,json=zitiServiceName,proto3" json:"ziti_service_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateServiceResponse) Reset() {
	*x = CreateServiceResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceResponse) ProtoMessage() {}

func (x *CreateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{9}
}

func (x *CreateServiceResponse) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

func (x *CreateServiceResponse) GetZitiServiceName() string {
	if x != nil {
		return x.ZitiServiceName
	}
	return ""
}

// Request to delete an app's OpenZiti identity and service by platform identity_id.
type DeleteAppIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform app identity UUID - for looking up managed identity
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// OpenZiti service ID - for deleting the OpenZiti service
	ZitiServiceId string `protobuf:"bytes,2,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppIdentityRequest) Reset() {
	*x = DeleteAppIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppIdentityRequest) ProtoMessage() {}

func (x *DeleteAppIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAppIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *DeleteAppIdentityRequest) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

// Response after deleting an app's OpenZiti identity.
type DeleteAppIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppIdentityResponse) Reset() {
	*x = DeleteAppIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppIdentityResponse) ProtoMessage() {}

func (x *DeleteAppIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{11}
}

type CreateRunnerIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunnerId       string                 `protobuf:"bytes,1,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	RoleAttributes []string               `protobuf:"bytes,2,rep,name=role_attributes,json=roleAttributes,proto3" json:"role_attributes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRunnerIdentityRequest) Reset() {
	*x = CreateRunnerIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerIdentityRequest) ProtoMessage() {}

func (x *CreateRunnerIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateRunnerIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRunnerIdentityRequest) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *CreateRunnerIdentityRequest) GetRoleAttributes() []string {
	if x != nil {
		return x.RoleAttributes
	}
	return nil
}

type CreateRunnerIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	IdentityJson   []byte                 `protobuf:"bytes,2,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRunnerIdentityResponse) Reset() {
	*x = CreateRunnerIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRunnerIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRunnerIdentityResponse) ProtoMessage() {}

func (x *CreateRunnerIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRunnerIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateRunnerIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRunnerIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateRunnerIdentityResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

type DeleteRunnerIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Platform runner UUID - for looking up managed identity
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// OpenZiti service ID - for deleting the OpenZiti service
	ZitiServiceId string `protobuf:"bytes,2,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerIdentityRequest) Reset() {
	*x = DeleteRunnerIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerIdentityRequest) ProtoMessage() {}

func (x *DeleteRunnerIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunnerIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRunnerIdentityRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *DeleteRunnerIdentityRequest) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

type DeleteRunnerIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunnerIdentityResponse) Reset() {
	*x = DeleteRunnerIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunnerIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunnerIdentityResponse) ProtoMessage() {}

func (x *DeleteRunnerIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunnerIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteRunnerIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{15}
}

type DeleteIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteIdentityRequest) Reset() {
	*x = DeleteIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityRequest) ProtoMessage() {}

func (x *DeleteIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type DeleteIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIdentityResponse) Reset() {
	*x = DeleteIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdentityResponse) ProtoMessage() {}

func (x *DeleteIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{17}
}

type ListManagedIdentitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityType  v1.IdentityType        `protobuf:"varint,1,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesRequest) Reset() {
	*x = ListManagedIdentitiesRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesRequest) ProtoMessage() {}

func (x *ListManagedIdentitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesRequest.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{18}
}

func (x *ListManagedIdentitiesRequest) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

func (x *ListManagedIdentitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListManagedIdentitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListManagedIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*ManagedIdentity     `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListManagedIdentitiesResponse) Reset() {
	*x = ListManagedIdentitiesResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListManagedIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListManagedIdentitiesResponse) ProtoMessage() {}

func (x *ListManagedIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListManagedIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListManagedIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{19}
}

func (x *ListManagedIdentitiesResponse) GetIdentities() []*ManagedIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *ListManagedIdentitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ResolveIdentityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitiIdentityId string                 `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveIdentityRequest) Reset() {
	*x = ResolveIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityRequest) ProtoMessage() {}

func (x *ResolveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type ResolveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	IdentityType  v1.IdentityType        `protobuf:"varint,2,opt,name=identity_type,json=identityType,proto3,enum=agynio.api.identity.v1.IdentityType" json:"identity_type,omitempty"`
	WorkloadId    *string                `protobuf:"bytes,3,opt,name=workload_id,json=workloadId,proto3,oneof" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentityResponse) Reset() {
	*x = ResolveIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentityResponse) ProtoMessage() {}

func (x *ResolveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentityResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{21}
}

func (x *ResolveIdentityResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ResolveIdentityResponse) GetIdentityType() v1.IdentityType {
	if x != nil {
		return x.IdentityType
	}
	return v1.IdentityType(0)
}

func (x *ResolveIdentityResponse) GetWorkloadId() string {
	if x != nil && x.WorkloadId != nil {
		return *x.WorkloadId
	}
	return ""
}

type RequestServiceIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which infrastructure service is requesting the identity.
	ServiceType   ServiceType `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=agynio.api.ziti_management.v1.ServiceType" json:"service_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceIdentityRequest) Reset() {
	*x = RequestServiceIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceIdentityRequest) ProtoMessage() {}

func (x *RequestServiceIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceIdentityRequest.ProtoReflect.Descriptor instead.
func (*RequestServiceIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{22}
}

func (x *RequestServiceIdentityRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_TYPE_UNSPECIFIED
}

type RequestServiceIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID (for lease extension and cleanup).
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	// The full enrolled identity JSON (contains cert, key, CA, controller URL).
	// The caller writes this to ephemeral disk and loads it via the OpenZiti SDK.
	IdentityJson  []byte `protobuf:"bytes,2,opt,name=identity_json,json=identityJson,proto3" json:"identity_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceIdentityResponse) Reset() {
	*x = RequestServiceIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceIdentityResponse) ProtoMessage() {}

func (x *RequestServiceIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceIdentityResponse.ProtoReflect.Descriptor instead.
func (*RequestServiceIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{23}
}

func (x *RequestServiceIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *RequestServiceIdentityResponse) GetIdentityJson() []byte {
	if x != nil {
		return x.IdentityJson
	}
	return nil
}

type ExtendIdentityLeaseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID whose lease should be extended.
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtendIdentityLeaseRequest) Reset() {
	*x = ExtendIdentityLeaseRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendIdentityLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendIdentityLeaseRequest) ProtoMessage() {}

func (x *ExtendIdentityLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendIdentityLeaseRequest.ProtoReflect.Descriptor instead.
func (*ExtendIdentityLeaseRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{24}
}

func (x *ExtendIdentityLeaseRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type ExtendIdentityLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendIdentityLeaseResponse) Reset() {
	*x = ExtendIdentityLeaseResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendIdentityLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendIdentityLeaseResponse) ProtoMessage() {}

func (x *ExtendIdentityLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendIdentityLeaseResponse.ProtoReflect.Descriptor instead.
func (*ExtendIdentityLeaseResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{25}
}

type CreateServicePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Policy type: Bind or Dial.
	Type ServicePolicyType `protobuf:"varint,1,opt,name=type,proto3,enum=agynio.api.ziti_management.v1.ServicePolicyType" json:"type,omitempty"`
	// Human-readable policy name (e.g. "exposed-<id>-bind").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Identity roles for the policy (e.g. ["#agent-<agentId>"] or ["#all"]).
	IdentityRoles []string `protobuf:"bytes,3,rep,name=identity_roles,json=identityRoles,proto3" json:"identity_roles,omitempty"`
	// Service roles for the policy (e.g. ["@exposed-<id>"]).
	ServiceRoles  []string `protobuf:"bytes,4,rep,name=service_roles,json=serviceRoles,proto3" json:"service_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServicePolicyRequest) Reset() {
	*x = CreateServicePolicyRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServicePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServicePolicyRequest) ProtoMessage() {}

func (x *CreateServicePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServicePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateServicePolicyRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{26}
}

func (x *CreateServicePolicyRequest) GetType() ServicePolicyType {
	if x != nil {
		return x.Type
	}
	return ServicePolicyType_SERVICE_POLICY_TYPE_UNSPECIFIED
}

func (x *CreateServicePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServicePolicyRequest) GetIdentityRoles() []string {
	if x != nil {
		return x.IdentityRoles
	}
	return nil
}

func (x *CreateServicePolicyRequest) GetServiceRoles() []string {
	if x != nil {
		return x.ServiceRoles
	}
	return nil
}

type CreateServicePolicyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti service policy ID.
	ZitiServicePolicyId string `protobuf:"bytes,1,opt,name=ziti_service_policy_id,json=zitiServicePolicyId,proto3" json:"ziti_service_policy_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateServicePolicyResponse) Reset() {
	*x = CreateServicePolicyResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServicePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServicePolicyResponse) ProtoMessage() {}

func (x *CreateServicePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServicePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreateServicePolicyResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{27}
}

func (x *CreateServicePolicyResponse) GetZitiServicePolicyId() string {
	if x != nil {
		return x.ZitiServicePolicyId
	}
	return ""
}

type DeleteServicePolicyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti service policy ID to delete.
	ZitiServicePolicyId string `protobuf:"bytes,1,opt,name=ziti_service_policy_id,json=zitiServicePolicyId,proto3" json:"ziti_service_policy_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeleteServicePolicyRequest) Reset() {
	*x = DeleteServicePolicyRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServicePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServicePolicyRequest) ProtoMessage() {}

func (x *DeleteServicePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServicePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteServicePolicyRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteServicePolicyRequest) GetZitiServicePolicyId() string {
	if x != nil {
		return x.ZitiServicePolicyId
	}
	return ""
}

type DeleteServicePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServicePolicyResponse) Reset() {
	*x = DeleteServicePolicyResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServicePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServicePolicyResponse) ProtoMessage() {}

func (x *DeleteServicePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServicePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeleteServicePolicyResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{29}
}

type DeleteServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti service ID to delete. Also deletes attached config objects.
	ZitiServiceId string `protobuf:"bytes,1,opt,name=ziti_service_id,json=zitiServiceId,proto3" json:"ziti_service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteServiceRequest) GetZitiServiceId() string {
	if x != nil {
		return x.ZitiServiceId
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{31}
}

type CreateDeviceIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owning user's platform identity ID.
	UserIdentityId string `protobuf:"bytes,1,opt,name=user_identity_id,json=userIdentityId,proto3" json:"user_identity_id,omitempty"`
	// User-provided device name.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceIdentityRequest) Reset() {
	*x = CreateDeviceIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceIdentityRequest) ProtoMessage() {}

func (x *CreateDeviceIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceIdentityRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{32}
}

func (x *CreateDeviceIdentityRequest) GetUserIdentityId() string {
	if x != nil {
		return x.UserIdentityId
	}
	return ""
}

func (x *CreateDeviceIdentityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDeviceIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID for this device.
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	// Enrollment JWT. Shown once to the user for their Ziti tunnel client.
	EnrollmentJwt string `protobuf:"bytes,2,opt,name=enrollment_jwt,json=enrollmentJwt,proto3" json:"enrollment_jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceIdentityResponse) Reset() {
	*x = CreateDeviceIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceIdentityResponse) ProtoMessage() {}

func (x *CreateDeviceIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceIdentityResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{33}
}

func (x *CreateDeviceIdentityResponse) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

func (x *CreateDeviceIdentityResponse) GetEnrollmentJwt() string {
	if x != nil {
		return x.EnrollmentJwt
	}
	return ""
}

type DeleteDeviceIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The OpenZiti identity ID of the device to delete.
	ZitiIdentityId string `protobuf:"bytes,1,opt,name=ziti_identity_id,json=zitiIdentityId,proto3" json:"ziti_identity_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteDeviceIdentityRequest) Reset() {
	*x = DeleteDeviceIdentityRequest{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceIdentityRequest) ProtoMessage() {}

func (x *DeleteDeviceIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceIdentityRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteDeviceIdentityRequest) GetZitiIdentityId() string {
	if x != nil {
		return x.ZitiIdentityId
	}
	return ""
}

type DeleteDeviceIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceIdentityResponse) Reset() {
	*x = DeleteDeviceIdentityResponse{}
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceIdentityResponse) ProtoMessage() {}

func (x *DeleteDeviceIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceIdentityResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeviceIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP(), []int{35}
}

var File_agynio_api_ziti_management_v1_ziti_management_proto protoreflect.FileDescriptor

const file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc = "" +
	"\n" +
	"3agynio/api/ziti_management/v1/ziti_management.proto\x12\x1dagynio.api.ziti_management.v1\x1a%agynio/api/identity/v1/identity.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x02\n" +
	"\x0fManagedIdentity\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x03 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\x12&\n" +
	"\x0fziti_service_id\x18\x04 \x01(\tR\rzitiServiceId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"X\n" +
	"\x1aCreateAgentIdentityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\"n\n" +
	"\x1bCreateAgentIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12%\n" +
	"\x0eenrollment_jwt\x18\x02 \x01(\tR\renrollmentJwt\"O\n" +
	"\x18CreateAppIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"\x81\x01\n" +
	"\x19CreateAppIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12#\n" +
	"\ridentity_json\x18\x02 \x01(\fR\fidentityJsonJ\x04\b\x03\x10\x04R\x0fziti_service_id\"X\n" +
	"\fHostV1Config\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\"\x9a\x01\n" +
	"\x11InterceptV1Config\x12\x1c\n" +
	"\tprotocols\x18\x01 \x03(\tR\tprotocols\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12I\n" +
	"\vport_ranges\x18\x03 \x03(\v2(.agynio.api.ziti_management.v1.PortRangeR\n" +
	"portRanges\"1\n" +
	"\tPortRange\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x05R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\"\xbd\x02\n" +
	"\x14CreateServiceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0frole_attributes\x18\x02 \x03(\tR\x0eroleAttributes\x12V\n" +
	"\x0ehost_v1_config\x18\x03 \x01(\v2+.agynio.api.ziti_management.v1.HostV1ConfigH\x00R\fhostV1Config\x88\x01\x01\x12e\n" +
	"\x13intercept_v1_config\x18\x04 \x01(\v20.agynio.api.ziti_management.v1.InterceptV1ConfigH\x01R\x11interceptV1Config\x88\x01\x01B\x11\n" +
	"\x0f_host_v1_configB\x16\n" +
	"\x14_intercept_v1_config\"k\n" +
	"\x15CreateServiceResponse\x12&\n" +
	"\x0fziti_service_id\x18\x01 \x01(\tR\rzitiServiceId\x12*\n" +
	"\x11ziti_service_name\x18\x02 \x01(\tR\x0fzitiServiceName\"c\n" +
	"\x18DeleteAppIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12&\n" +
	"\x0fziti_service_id\x18\x02 \x01(\tR\rzitiServiceId\"\x1b\n" +
	"\x19DeleteAppIdentityResponse\"c\n" +
	"\x1bCreateRunnerIdentityRequest\x12\x1b\n" +
	"\trunner_id\x18\x01 \x01(\tR\brunnerId\x12'\n" +
	"\x0frole_attributes\x18\x02 \x03(\tR\x0eroleAttributes\"\x9d\x01\n" +
	"\x1cCreateRunnerIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12#\n" +
	"\ridentity_json\x18\x02 \x01(\fR\fidentityJsonJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05R\x0fziti_service_idR\x11ziti_service_name\"f\n" +
	"\x1bDeleteRunnerIdentityRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12&\n" +
	"\x0fziti_service_id\x18\x02 \x01(\tR\rzitiServiceId\"\x1e\n" +
	"\x1cDeleteRunnerIdentityResponse\"A\n" +
	"\x15DeleteIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x18\n" +
	"\x16DeleteIdentityResponse\"\xa5\x01\n" +
	"\x1cListManagedIdentitiesRequest\x12I\n" +
	"\ridentity_type\x18\x01 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x97\x01\n" +
	"\x1dListManagedIdentitiesResponse\x12N\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2..agynio.api.ziti_management.v1.ManagedIdentityR\n" +
	"identities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x16ResolveIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\xbb\x01\n" +
	"\x17ResolveIdentityResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12I\n" +
	"\ridentity_type\x18\x02 \x01(\x0e2$.agynio.api.identity.v1.IdentityTypeR\fidentityType\x12$\n" +
	"\vworkload_id\x18\x03 \x01(\tH\x00R\n" +
	"workloadId\x88\x01\x01B\x0e\n" +
	"\f_workload_id\"n\n" +
	"\x1dRequestServiceIdentityRequest\x12M\n" +
	"\fservice_type\x18\x01 \x01(\x0e2*.agynio.api.ziti_management.v1.ServiceTypeR\vserviceType\"o\n" +
	"\x1eRequestServiceIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12#\n" +
	"\ridentity_json\x18\x02 \x01(\fR\fidentityJson\"F\n" +
	"\x1aExtendIdentityLeaseRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x1d\n" +
	"\x1bExtendIdentityLeaseResponse\"\xc2\x01\n" +
	"\x1aCreateServicePolicyRequest\x12D\n" +
	"\x04type\x18\x01 \x01(\x0e20.agynio.api.ziti_management.v1.ServicePolicyTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eidentity_roles\x18\x03 \x03(\tR\ridentityRoles\x12#\n" +
	"\rservice_roles\x18\x04 \x03(\tR\fserviceRoles\"R\n" +
	"\x1bCreateServicePolicyResponse\x123\n" +
	"\x16ziti_service_policy_id\x18\x01 \x01(\tR\x13zitiServicePolicyId\"Q\n" +
	"\x1aDeleteServicePolicyRequest\x123\n" +
	"\x16ziti_service_policy_id\x18\x01 \x01(\tR\x13zitiServicePolicyId\"\x1d\n" +
	"\x1bDeleteServicePolicyResponse\">\n" +
	"\x14DeleteServiceRequest\x12&\n" +
	"\x0fziti_service_id\x18\x01 \x01(\tR\rzitiServiceId\"\x17\n" +
	"\x15DeleteServiceResponse\"[\n" +
	"\x1bCreateDeviceIdentityRequest\x12(\n" +
	"\x10user_identity_id\x18\x01 \x01(\tR\x0euserIdentityId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"o\n" +
	"\x1cCreateDeviceIdentityResponse\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\x12%\n" +
	"\x0eenrollment_jwt\x18\x02 \x01(\tR\renrollmentJwt\"G\n" +
	"\x1bDeleteDeviceIdentityRequest\x12(\n" +
	"\x10ziti_identity_id\x18\x01 \x01(\tR\x0ezitiIdentityId\"\x1e\n" +
	"\x1cDeleteDeviceIdentityResponse*\xb5\x01\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVICE_TYPE_GATEWAY\x10\x01\x12\x1d\n" +
	"\x19SERVICE_TYPE_ORCHESTRATOR\x10\x02\x12\x1a\n" +
	"\x16SERVICE_TYPE_LLM_PROXY\x10\x04\x12\x18\n" +
	"\x14SERVICE_TYPE_TRACING\x10\x05\"\x04\b\x03\x10\x03*\x13SERVICE_TYPE_RUNNER*t\n" +
	"\x11ServicePolicyType\x12#\n" +
	"\x1fSERVICE_POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SERVICE_POLICY_TYPE_BIND\x10\x01\x12\x1c\n" +
	"\x18SERVICE_POLICY_TYPE_DIAL\x10\x022\xd4\x11\n" +
	"\x15ZitiManagementService\x12\x8c\x01\n" +
	"\x13CreateAgentIdentity\x129.agynio.api.ziti_management.v1.CreateAgentIdentityRequest\x1a:.agynio.api.ziti_management.v1.CreateAgentIdentityResponse\x12\x86\x01\n" +
	"\x11CreateAppIdentity\x127.agynio.api.ziti_management.v1.CreateAppIdentityRequest\x1a8.agynio.api.ziti_management.v1.CreateAppIdentityResponse\x12z\n" +
	"\rCreateService\x123.agynio.api.ziti_management.v1.CreateServiceRequest\x1a4.agynio.api.ziti_management.v1.CreateServiceResponse\x12}\n" +
	"\x0eDeleteIdentity\x124.agynio.api.ziti_management.v1.DeleteIdentityRequest\x1a5.agynio.api.ziti_management.v1.DeleteIdentityResponse\x12\x86\x01\n" +
	"\x11DeleteAppIdentity\x127.agynio.api.ziti_management.v1.DeleteAppIdentityRequest\x1a8.agynio.api.ziti_management.v1.DeleteAppIdentityResponse\x12\x8f\x01\n" +
	"\x14CreateRunnerIdentity\x12:.agynio.api.ziti_management.v1.CreateRunnerIdentityRequest\x1a;.agynio.api.ziti_management.v1.CreateRunnerIdentityResponse\x12\x8f\x01\n" +
	"\x14DeleteRunnerIdentity\x12:.agynio.api.ziti_management.v1.DeleteRunnerIdentityRequest\x1a;.agynio.api.ziti_management.v1.DeleteRunnerIdentityResponse\x12\x92\x01\n" +
	"\x15ListManagedIdentities\x12;.agynio.api.ziti_management.v1.ListManagedIdentitiesRequest\x1a<.agynio.api.ziti_management.v1.ListManagedIdentitiesResponse\x12\x80\x01\n" +
	"\x0fResolveIdentity\x125.agynio.api.ziti_management.v1.ResolveIdentityRequest\x1a6.agynio.api.ziti_management.v1.ResolveIdentityResponse\x12\x95\x01\n" +
	"\x16RequestServiceIdentity\x12<.agynio.api.ziti_management.v1.RequestServiceIdentityRequest\x1a=.agynio.api.ziti_management.v1.RequestServiceIdentityResponse\x12\x8c\x01\n" +
	"\x13ExtendIdentityLease\x129.agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest\x1a:.agynio.api.ziti_management.v1.ExtendIdentityLeaseResponse\x12\x8c\x01\n" +
	"\x13CreateServicePolicy\x129.agynio.api.ziti_management.v1.CreateServicePolicyRequest\x1a:.agynio.api.ziti_management.v1.CreateServicePolicyResponse\x12\x8c\x01\n" +
	"\x13DeleteServicePolicy\x129.agynio.api.ziti_management.v1.DeleteServicePolicyRequest\x1a:.agynio.api.ziti_management.v1.DeleteServicePolicyResponse\x12z\n" +
	"\rDeleteService\x123.agynio.api.ziti_management.v1.DeleteServiceRequest\x1a4.agynio.api.ziti_management.v1.DeleteServiceResponse\x12\x8f\x01\n" +
	"\x14CreateDeviceIdentity\x12:.agynio.api.ziti_management.v1.CreateDeviceIdentityRequest\x1a;.agynio.api.ziti_management.v1.CreateDeviceIdentityResponse\x12\x8f\x01\n" +
	"\x14DeleteDeviceIdentity\x12:.agynio.api.ziti_management.v1.DeleteDeviceIdentityRequest\x1a;.agynio.api.ziti_management.v1.DeleteDeviceIdentityResponseB\x9e\x02\n" +
	"!com.agynio.api.ziti_management.v1B\x13ZitiManagementProtoP\x01ZQgithub.com/agynio/tracing/.gen/go/agynio/api/ziti_management/v1;ziti_managementv1\xa2\x02\x03AAZ\xaa\x02\x1cAgynio.Api.ZitiManagement.V1\xca\x02\x1cAgynio\\Api\\ZitiManagement\\V1\xe2\x02(Agynio\\Api\\ZitiManagement\\V1\\GPBMetadata\xea\x02\x1fAgynio::Api::ZitiManagement::V1b\x06proto3"

var (
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce sync.Once
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData []byte
)

func file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescGZIP() []byte {
	file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescOnce.Do(func() {
		file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)))
	})
	return file_agynio_api_ziti_management_v1_ziti_management_proto_rawDescData
}

var file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = []any{
	(ServiceType)(0),                       // 0: agynio.api.ziti_management.v1.ServiceType
	(ServicePolicyType)(0),                 // 1: agynio.api.ziti_management.v1.ServicePolicyType
	(*ManagedIdentity)(nil),                // 2: agynio.api.ziti_management.v1.ManagedIdentity
	(*CreateAgentIdentityRequest)(nil),     // 3: agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	(*CreateAgentIdentityResponse)(nil),    // 4: agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	(*CreateAppIdentityRequest)(nil),       // 5: agynio.api.ziti_management.v1.CreateAppIdentityRequest
	(*CreateAppIdentityResponse)(nil),      // 6: agynio.api.ziti_management.v1.CreateAppIdentityResponse
	(*HostV1Config)(nil),                   // 7: agynio.api.ziti_management.v1.HostV1Config
	(*InterceptV1Config)(nil),              // 8: agynio.api.ziti_management.v1.InterceptV1Config
	(*PortRange)(nil),                      // 9: agynio.api.ziti_management.v1.PortRange
	(*CreateServiceRequest)(nil),           // 10: agynio.api.ziti_management.v1.CreateServiceRequest
	(*CreateServiceResponse)(nil),          // 11: agynio.api.ziti_management.v1.CreateServiceResponse
	(*DeleteAppIdentityRequest)(nil),       // 12: agynio.api.ziti_management.v1.DeleteAppIdentityRequest
	(*DeleteAppIdentityResponse)(nil),      // 13: agynio.api.ziti_management.v1.DeleteAppIdentityResponse
	(*CreateRunnerIdentityRequest)(nil),    // 14: agynio.api.ziti_management.v1.CreateRunnerIdentityRequest
	(*CreateRunnerIdentityResponse)(nil),   // 15: agynio.api.ziti_management.v1.CreateRunnerIdentityResponse
	(*DeleteRunnerIdentityRequest)(nil),    // 16: agynio.api.ziti_management.v1.DeleteRunnerIdentityRequest
	(*DeleteRunnerIdentityResponse)(nil),   // 17: agynio.api.ziti_management.v1.DeleteRunnerIdentityResponse
	(*DeleteIdentityRequest)(nil),          // 18: agynio.api.ziti_management.v1.DeleteIdentityRequest
	(*DeleteIdentityResponse)(nil),         // 19: agynio.api.ziti_management.v1.DeleteIdentityResponse
	(*ListManagedIdentitiesRequest)(nil),   // 20: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	(*ListManagedIdentitiesResponse)(nil),  // 21: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	(*ResolveIdentityRequest)(nil),         // 22: agynio.api.ziti_management.v1.ResolveIdentityRequest
	(*ResolveIdentityResponse)(nil),        // 23: agynio.api.ziti_management.v1.ResolveIdentityResponse
	(*RequestServiceIdentityRequest)(nil),  // 24: agynio.api.ziti_management.v1.RequestServiceIdentityRequest
	(*RequestServiceIdentityResponse)(nil), // 25: agynio.api.ziti_management.v1.RequestServiceIdentityResponse
	(*ExtendIdentityLeaseRequest)(nil),     // 26: agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest
	(*ExtendIdentityLeaseResponse)(nil),    // 27: agynio.api.ziti_management.v1.ExtendIdentityLeaseResponse
	(*CreateServicePolicyRequest)(nil),     // 28: agynio.api.ziti_management.v1.CreateServicePolicyRequest
	(*CreateServicePolicyResponse)(nil),    // 29: agynio.api.ziti_management.v1.CreateServicePolicyResponse
	(*DeleteServicePolicyRequest)(nil),     // 30: agynio.api.ziti_management.v1.DeleteServicePolicyRequest
	(*DeleteServicePolicyResponse)(nil),    // 31: agynio.api.ziti_management.v1.DeleteServicePolicyResponse
	(*DeleteServiceRequest)(nil),           // 32: agynio.api.ziti_management.v1.DeleteServiceRequest
	(*DeleteServiceResponse)(nil),          // 33: agynio.api.ziti_management.v1.DeleteServiceResponse
	(*CreateDeviceIdentityRequest)(nil),    // 34: agynio.api.ziti_management.v1.CreateDeviceIdentityRequest
	(*CreateDeviceIdentityResponse)(nil),   // 35: agynio.api.ziti_management.v1.CreateDeviceIdentityResponse
	(*DeleteDeviceIdentityRequest)(nil),    // 36: agynio.api.ziti_management.v1.DeleteDeviceIdentityRequest
	(*DeleteDeviceIdentityResponse)(nil),   // 37: agynio.api.ziti_management.v1.DeleteDeviceIdentityResponse
	(v1.IdentityType)(0),                   // 38: agynio.api.identity.v1.IdentityType
	(*timestamppb.Timestamp)(nil),          // 39: google.protobuf.Timestamp
}
var file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = []int32{
	38, // 0: agynio.api.ziti_management.v1.ManagedIdentity.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	39, // 1: agynio.api.ziti_management.v1.ManagedIdentity.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: agynio.api.ziti_management.v1.InterceptV1Config.port_ranges:type_name -> agynio.api.ziti_management.v1.PortRange
	7,  // 3: agynio.api.ziti_management.v1.CreateServiceRequest.host_v1_config:type_name -> agynio.api.ziti_management.v1.HostV1Config
	8,  // 4: agynio.api.ziti_management.v1.CreateServiceRequest.intercept_v1_config:type_name -> agynio.api.ziti_management.v1.InterceptV1Config
	38, // 5: agynio.api.ziti_management.v1.ListManagedIdentitiesRequest.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	2,  // 6: agynio.api.ziti_management.v1.ListManagedIdentitiesResponse.identities:type_name -> agynio.api.ziti_management.v1.ManagedIdentity
	38, // 7: agynio.api.ziti_management.v1.ResolveIdentityResponse.identity_type:type_name -> agynio.api.identity.v1.IdentityType
	0,  // 8: agynio.api.ziti_management.v1.RequestServiceIdentityRequest.service_type:type_name -> agynio.api.ziti_management.v1.ServiceType
	1,  // 9: agynio.api.ziti_management.v1.CreateServicePolicyRequest.type:type_name -> agynio.api.ziti_management.v1.ServicePolicyType
	3,  // 10: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:input_type -> agynio.api.ziti_management.v1.CreateAgentIdentityRequest
	5,  // 11: agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity:input_type -> agynio.api.ziti_management.v1.CreateAppIdentityRequest
	10, // 12: agynio.api.ziti_management.v1.ZitiManagementService.CreateService:input_type -> agynio.api.ziti_management.v1.CreateServiceRequest
	18, // 13: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:input_type -> agynio.api.ziti_management.v1.DeleteIdentityRequest
	12, // 14: agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity:input_type -> agynio.api.ziti_management.v1.DeleteAppIdentityRequest
	14, // 15: agynio.api.ziti_management.v1.ZitiManagementService.CreateRunnerIdentity:input_type -> agynio.api.ziti_management.v1.CreateRunnerIdentityRequest
	16, // 16: agynio.api.ziti_management.v1.ZitiManagementService.DeleteRunnerIdentity:input_type -> agynio.api.ziti_management.v1.DeleteRunnerIdentityRequest
	20, // 17: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:input_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesRequest
	22, // 18: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:input_type -> agynio.api.ziti_management.v1.ResolveIdentityRequest
	24, // 19: agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity:input_type -> agynio.api.ziti_management.v1.RequestServiceIdentityRequest
	26, // 20: agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease:input_type -> agynio.api.ziti_management.v1.ExtendIdentityLeaseRequest
	28, // 21: agynio.api.ziti_management.v1.ZitiManagementService.CreateServicePolicy:input_type -> agynio.api.ziti_management.v1.CreateServicePolicyRequest
	30, // 22: agynio.api.ziti_management.v1.ZitiManagementService.DeleteServicePolicy:input_type -> agynio.api.ziti_management.v1.DeleteServicePolicyRequest
	32, // 23: agynio.api.ziti_management.v1.ZitiManagementService.DeleteService:input_type -> agynio.api.ziti_management.v1.DeleteServiceRequest
	34, // 24: agynio.api.ziti_management.v1.ZitiManagementService.CreateDeviceIdentity:input_type -> agynio.api.ziti_management.v1.CreateDeviceIdentityRequest
	36, // 25: agynio.api.ziti_management.v1.ZitiManagementService.DeleteDeviceIdentity:input_type -> agynio.api.ziti_management.v1.DeleteDeviceIdentityRequest
	4,  // 26: agynio.api.ziti_management.v1.ZitiManagementService.CreateAgentIdentity:output_type -> agynio.api.ziti_management.v1.CreateAgentIdentityResponse
	6,  // 27: agynio.api.ziti_management.v1.ZitiManagementService.CreateAppIdentity:output_type -> agynio.api.ziti_management.v1.CreateAppIdentityResponse
	11, // 28: agynio.api.ziti_management.v1.ZitiManagementService.CreateService:output_type -> agynio.api.ziti_management.v1.CreateServiceResponse
	19, // 29: agynio.api.ziti_management.v1.ZitiManagementService.DeleteIdentity:output_type -> agynio.api.ziti_management.v1.DeleteIdentityResponse
	13, // 30: agynio.api.ziti_management.v1.ZitiManagementService.DeleteAppIdentity:output_type -> agynio.api.ziti_management.v1.DeleteAppIdentityResponse
	15, // 31: agynio.api.ziti_management.v1.ZitiManagementService.CreateRunnerIdentity:output_type -> agynio.api.ziti_management.v1.CreateRunnerIdentityResponse
	17, // 32: agynio.api.ziti_management.v1.ZitiManagementService.DeleteRunnerIdentity:output_type -> agynio.api.ziti_management.v1.DeleteRunnerIdentityResponse
	21, // 33: agynio.api.ziti_management.v1.ZitiManagementService.ListManagedIdentities:output_type -> agynio.api.ziti_management.v1.ListManagedIdentitiesResponse
	23, // 34: agynio.api.ziti_management.v1.ZitiManagementService.ResolveIdentity:output_type -> agynio.api.ziti_management.v1.ResolveIdentityResponse
	25, // 35: agynio.api.ziti_management.v1.ZitiManagementService.RequestServiceIdentity:output_type -> agynio.api.ziti_management.v1.RequestServiceIdentityResponse
	27, // 36: agynio.api.ziti_management.v1.ZitiManagementService.ExtendIdentityLease:output_type -> agynio.api.ziti_management.v1.ExtendIdentityLeaseResponse
	29, // 37: agynio.api.ziti_management.v1.ZitiManagementService.CreateServicePolicy:output_type -> agynio.api.ziti_management.v1.CreateServicePolicyResponse
	31, // 38: agynio.api.ziti_management.v1.ZitiManagementService.DeleteServicePolicy:output_type -> agynio.api.ziti_management.v1.DeleteServicePolicyResponse
	33, // 39: agynio.api.ziti_management.v1.ZitiManagementService.DeleteService:output_type -> agynio.api.ziti_management.v1.DeleteServiceResponse
	35, // 40: agynio.api.ziti_management.v1.ZitiManagementService.CreateDeviceIdentity:output_type -> agynio.api.ziti_management.v1.CreateDeviceIdentityResponse
	37, // 41: agynio.api.ziti_management.v1.ZitiManagementService.DeleteDeviceIdentity:output_type -> agynio.api.ziti_management.v1.DeleteDeviceIdentityResponse
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agynio_api_ziti_management_v1_ziti_management_proto_init() }
func file_agynio_api_ziti_management_v1_ziti_management_proto_init() {
	if File_agynio_api_ziti_management_v1_ziti_management_proto != nil {
		return
	}
	file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[8].OneofWrappers = []any{}
	file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc), len(file_agynio_api_ziti_management_v1_ziti_management_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes,
		DependencyIndexes: file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs,
		EnumInfos:         file_agynio_api_ziti_management_v1_ziti_management_proto_enumTypes,
		MessageInfos:      file_agynio_api_ziti_management_v1_ziti_management_proto_msgTypes,
	}.Build()
	File_agynio_api_ziti_management_v1_ziti_management_proto = out.File
	file_agynio_api_ziti_management_v1_ziti_management_proto_goTypes = nil
	file_agynio_api_ziti_management_v1_ziti_management_proto_depIdxs = nil
}
